/**
 * validateResult.js
 * 
 * Defensive client-side structural validator.
 * Validates that data received from the backend (originally generated by LLM)
 * strictly matches the required shape for Flashcards, Quiz, and Dashboard components.
 * 
 * Never renders unvalidated data to the UI.
 */

/**
 * Validates that an object conforms to the StudySet schema.
 * @param {any} data - Raw or parsed data object to validate
 * @returns {{ isValid: boolean, error?: string, data?: object }}
 */
export function validateStudySet(data) {
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    return {
      isValid: false,
      error: 'Data payload is not a valid JSON object.',
    };
  }

  // 1. Title validation
  if (!data.title || typeof data.title !== 'string' || data.title.trim().length === 0) {
    return {
      isValid: false,
      error: 'Missing or invalid "title" field in study set.',
    };
  }

  // 2. Summary
  const summary = typeof data.summary === 'string' && data.summary.trim().length > 0
    ? data.summary.trim()
    : 'Comprehensive study set covering key concepts, mechanisms, and practice questions.';

  // 3. Metadata validation with safe fallbacks
  const metadata = {
    difficulty: ['beginner', 'intermediate', 'advanced'].includes(data.metadata?.difficulty?.toLowerCase())
      ? data.metadata.difficulty.toLowerCase()
      : 'intermediate',
    mode: ['balanced', 'concept', 'exam'].includes(data.metadata?.mode?.toLowerCase())
      ? data.metadata.mode.toLowerCase()
      : 'balanced',
    estimatedMinutes: typeof data.metadata?.estimatedMinutes === 'number' && data.metadata.estimatedMinutes > 0
      ? data.metadata.estimatedMinutes
      : Math.max(Math.round(((data.cards?.length || 8) * 1.5) + ((data.quiz?.length || 5) * 1.2)), 5),
    topics: Array.isArray(data.metadata?.topics) && data.metadata.topics.length > 0
      ? data.metadata.topics.filter((t) => typeof t === 'string' && t.trim().length > 0).map((t) => t.trim())
      : ['Core Principles', 'Key Distinctions', 'Practical Application'],
  };

  // 4. Cards array validation
  if (!Array.isArray(data.cards) || data.cards.length === 0) {
    return {
      isValid: false,
      error: 'Study set must contain a non-empty "cards" array.',
    };
  }

  const seenCardIds = new Set();
  const seenCardQuestions = new Set();

  for (let i = 0; i < data.cards.length; i++) {
    const card = data.cards[i];
    if (!card || typeof card !== 'object') {
      return {
        isValid: false,
        error: `Flashcard #${i + 1} is not a valid object.`,
      };
    }
    if (!card.question || typeof card.question !== 'string' || card.question.trim().length === 0) {
      return {
        isValid: false,
        error: `Flashcard #${i + 1} is missing a valid "question" string.`,
      };
    }

    const qNorm = card.question.trim().toLowerCase();
    if (seenCardQuestions.has(qNorm)) {
      return {
        isValid: false,
        error: `Flashcard #${i + 1} is a duplicate question.`,
      };
    }
    seenCardQuestions.add(qNorm);

    if (!card.answer || typeof card.answer !== 'string' || card.answer.trim().length === 0) {
      return {
        isValid: false,
        error: `Flashcard #${i + 1} is missing a valid "answer" string.`,
      };
    }

    if (card.question.trim().toLowerCase() === card.answer.trim().toLowerCase()) {
      return {
        isValid: false,
        error: `Flashcard #${i + 1} question and answer cannot be identical.`,
      };
    }
  }

  // 5. Quiz array validation
  if (!Array.isArray(data.quiz) || data.quiz.length === 0) {
    return {
      isValid: false,
      error: 'Study set must contain a non-empty "quiz" array.',
    };
  }

  const seenQuizQuestions = new Set();

  for (let i = 0; i < data.quiz.length; i++) {
    const q = data.quiz[i];
    if (!q || typeof q !== 'object') {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} is not a valid object.`,
      };
    }
    if (!q.question || typeof q.question !== 'string' || q.question.trim().length === 0) {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} is missing a valid "question" string.`,
      };
    }

    const qNorm = q.question.trim().toLowerCase();
    if (seenQuizQuestions.has(qNorm)) {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} is a duplicate question.`,
      };
    }
    seenQuizQuestions.add(qNorm);

    if (!Array.isArray(q.options) || q.options.length !== 4) {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} must have exactly 4 options. Found: ${Array.isArray(q.options) ? q.options.length : 'none'}.`,
      };
    }
    for (let optIdx = 0; optIdx < q.options.length; optIdx++) {
      const opt = q.options[optIdx];
      if (typeof opt !== 'string' || opt.trim().length === 0) {
        return {
          isValid: false,
          error: `Quiz question #${i + 1}, option #${optIdx + 1} is empty or not a string.`,
        };
      }
    }
    if (
      typeof q.answer !== 'number' ||
      !Number.isInteger(q.answer) ||
      q.answer < 0 ||
      q.answer > 3
    ) {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} answer must be an integer index between 0 and 3. Received: ${q.answer}.`,
      };
    }
    if (!q.explanation || typeof q.explanation !== 'string' || q.explanation.trim().length === 0) {
      return {
        isValid: false,
        error: `Quiz question #${i + 1} is missing an "explanation" string.`,
      };
    }
  }

  // 6. Return sanitized structure with guaranteed STABLE IDs for React keys and quiz result mapping
  const sanitized = {
    title: data.title.trim(),
    summary,
    metadata,
    cards: data.cards.map((c, i) => {
      const cardId = c.id && typeof c.id === 'string' && !seenCardIds.has(c.id) ? c.id : `card-${i + 1}`;
      seenCardIds.add(cardId);
      return {
        id: cardId,
        category: typeof c.category === 'string' && c.category.trim() ? c.category.trim() : 'Core Concept',
        question: c.question.trim(),
        answer: c.answer.trim(),
        difficulty: ['easy', 'medium', 'hard'].includes(c.difficulty?.toLowerCase())
          ? c.difficulty.toLowerCase()
          : metadata.difficulty === 'beginner' ? 'easy' : metadata.difficulty === 'advanced' ? 'hard' : 'medium',
      };
    }),
    quiz: data.quiz.map((q, i) => {
      const quizId = q.id && typeof q.id === 'string' ? q.id : `quiz-${i + 1}`;
      return {
        id: quizId,
        category: typeof q.category === 'string' && q.category.trim() ? q.category.trim() : 'Concept Check',
        question: q.question.trim(),
        options: q.options.map((opt) => opt.trim()),
        answer: q.answer,
        explanation: q.explanation.trim(),
        difficulty: ['easy', 'medium', 'hard'].includes(q.difficulty?.toLowerCase())
          ? q.difficulty.toLowerCase()
          : metadata.difficulty === 'beginner' ? 'easy' : metadata.difficulty === 'advanced' ? 'hard' : 'medium',
      };
    }),
  };

  return {
    isValid: true,
    data: sanitized,
  };
}
