import express from 'express';
import http from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { StudyRoomManager, sanitizeMessage } from './studyRoomManager.js';

// Resolve project root directory and load .env
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env') });
dotenv.config(); // fallback to current working directory

const app = express();
const httpServer = http.createServer(app);
const io = new Server(httpServer, {
  cors: {
    origin: '*',
    methods: ['GET', 'POST'],
  },
});

const PORT = process.env.PORT || 5000;
const roomManager = new StudyRoomManager(io, () => process.env.GEMINI_API_KEY);

// Enable CORS and JSON body parser with safe limit
app.use(cors());
app.use(express.json({ limit: '500kb' }));

/**
 * Health check endpoint
 */
app.get('/api/health', (req, res) => {
  const apiKey = process.env.GEMINI_API_KEY;
  const isConfigured = Boolean(apiKey && apiKey !== 'your_gemini_api_key_here' && apiKey.trim() !== '');
  res.json({
    status: 'ok',
    geminiConfigured: isConfigured,
    mode: isConfigured ? 'live_gemini' : 'demo_fallback',
    timestamp: new Date().toISOString(),
  });
});

/**
 * Validates and sanitizes the structured study set generated by the AI model or demo generator.
 */
function validateAndSanitizeStudySet(data, expectedConfig = {}) {
  const errors = [];

  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    return { valid: false, errors: ['Response must be a JSON object'] };
  }

  // 1. Validate title
  if (!data.title || typeof data.title !== 'string' || data.title.trim().length === 0) {
    errors.push('Field "title" must be a non-empty string');
  }

  // 2. Validate summary
  const summary = typeof data.summary === 'string' && data.summary.trim().length > 0
    ? data.summary.trim()
    : 'Comprehensive study set covering key concepts, mechanisms, and practice questions.';

  // 3. Validate metadata
  const metadata = {
    difficulty: ['beginner', 'intermediate', 'advanced'].includes(data.metadata?.difficulty?.toLowerCase())
      ? data.metadata.difficulty.toLowerCase()
      : (expectedConfig.difficulty || 'intermediate'),
    mode: ['balanced', 'concept', 'exam'].includes(data.metadata?.mode?.toLowerCase())
      ? data.metadata.mode.toLowerCase()
      : (expectedConfig.mode || 'balanced'),
    estimatedMinutes: typeof data.metadata?.estimatedMinutes === 'number' && data.metadata.estimatedMinutes > 0
      ? Math.min(Math.max(data.metadata.estimatedMinutes, 5), 60)
      : Math.max(Math.round(((data.cards?.length || 8) * 1.5) + ((data.quiz?.length || 5) * 1.2)), 5),
    topics: Array.isArray(data.metadata?.topics) && data.metadata.topics.length > 0
      ? data.metadata.topics.filter(t => typeof t === 'string' && t.trim().length > 0).map(t => t.trim())
      : ['Core Principles', 'Key Distinctions', 'Practical Application'],
  };

  // 4. Validate cards
  if (!Array.isArray(data.cards) || data.cards.length === 0) {
    errors.push('Field "cards" must be a non-empty array of flashcard objects');
  } else {
    const cardQuestions = new Set();
    data.cards.forEach((card, index) => {
      if (!card || typeof card !== 'object') {
        errors.push(`Card at index ${index} must be an object`);
        return;
      }
      if (!card.question || typeof card.question !== 'string' || card.question.trim().length === 0) {
        errors.push(`Card ${index + 1} is missing a valid "question" string`);
      } else {
        const qNorm = card.question.trim().toLowerCase();
        if (cardQuestions.has(qNorm)) {
          errors.push(`Card ${index + 1} is a duplicate of another card question`);
        }
        cardQuestions.add(qNorm);
      }
      if (!card.answer || typeof card.answer !== 'string' || card.answer.trim().length === 0) {
        errors.push(`Card ${index + 1} is missing a valid "answer" string`);
      } else if (card.question && card.question.trim().toLowerCase() === card.answer.trim().toLowerCase()) {
        errors.push(`Card ${index + 1} question and answer cannot be identical`);
      }
    });
  }

  // 5. Validate quiz
  if (!Array.isArray(data.quiz) || data.quiz.length === 0) {
    errors.push('Field "quiz" must be a non-empty array of quiz question objects');
  } else {
    const quizQuestions = new Set();
    data.quiz.forEach((q, index) => {
      if (!q || typeof q !== 'object') {
        errors.push(`Quiz item at index ${index} must be an object`);
        return;
      }
      if (!q.question || typeof q.question !== 'string' || q.question.trim().length === 0) {
        errors.push(`Quiz question ${index + 1} is missing a valid "question" string`);
      } else {
        const qNorm = q.question.trim().toLowerCase();
        if (quizQuestions.has(qNorm)) {
          errors.push(`Quiz question ${index + 1} is a duplicate of another quiz question`);
        }
        quizQuestions.add(qNorm);
      }
      if (!Array.isArray(q.options) || q.options.length !== 4) {
        errors.push(`Quiz question ${index + 1} must have an "options" array with exactly 4 choices`);
      } else {
        const hasInvalidOption = q.options.some((opt) => typeof opt !== 'string' || opt.trim().length === 0);
        if (hasInvalidOption) {
          errors.push(`Quiz question ${index + 1} contains empty or non-string options`);
        }
        const uniqueOptions = new Set(q.options.map(o => typeof o === 'string' ? o.trim().toLowerCase() : ''));
        if (uniqueOptions.size < 3) {
          errors.push(`Quiz question ${index + 1} options must be distinct`);
        }
      }
      if (
        typeof q.answer !== 'number' ||
        !Number.isInteger(q.answer) ||
        q.answer < 0 ||
        q.answer > 3
      ) {
        errors.push(`Quiz question ${index + 1} "answer" must be an integer between 0 and 3`);
      }
      if (!q.explanation || typeof q.explanation !== 'string' || q.explanation.trim().length === 0) {
        errors.push(`Quiz question ${index + 1} is missing a valid "explanation" string`);
      }
    });
  }

  if (errors.length > 0) {
    return { valid: false, errors };
  }

  const sanitizedData = {
    title: data.title.trim(),
    summary,
    metadata,
    cards: data.cards.map((c, i) => ({
      id: `card-${i + 1}`,
      category: typeof c.category === 'string' && c.category.trim() ? c.category.trim() : 'Core Concept',
      question: c.question.trim(),
      answer: c.answer.trim(),
      difficulty: ['easy', 'medium', 'hard'].includes(c.difficulty?.toLowerCase())
        ? c.difficulty.toLowerCase()
        : metadata.difficulty === 'beginner' ? 'easy' : metadata.difficulty === 'advanced' ? 'hard' : 'medium',
    })),
    quiz: data.quiz.map((q, i) => ({
      id: `quiz-${i + 1}`,
      category: typeof q.category === 'string' && q.category.trim() ? q.category.trim() : 'Concept Check',
      question: q.question.trim(),
      options: q.options.map((opt) => opt.trim()),
      answer: q.answer,
      explanation: q.explanation.trim(),
      difficulty: ['easy', 'medium', 'hard'].includes(q.difficulty?.toLowerCase())
        ? q.difficulty.toLowerCase()
        : metadata.difficulty === 'beginner' ? 'easy' : metadata.difficulty === 'advanced' ? 'hard' : 'medium',
    })),
  };

  return { valid: true, errors: [], sanitizedData };
}

/**
 * Strips accidental markdown code blocks (```json ... ```) or whitespace
 */
function cleanRawJsonResponse(raw) {
  let cleaned = raw.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json\s*/i, '').replace(/\s*```$/, '');
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```\s*/, '').replace(/\s*```$/, '');
  }
  return cleaned.trim();
}

/**
 * Attempts Gemini LLM generation with automatic model fallback
 */
async function callGeminiWithFallback(apiKey, systemInstruction, userPrompt) {
  const genAI = new GoogleGenerativeAI(apiKey);
  const candidateModels = [
    'gemini-3.5-flash-lite',
    'gemini-3.8-flash'
  ];
  let lastError = null;
  for (const modelName of candidateModels) {
    try {
      const model = genAI.getGenerativeModel({
        model: modelName,
        generationConfig: {
          responseMimeType: 'application/json',
          temperature: 0.2,
        },
      });

      const result = await model.generateContent([
        { text: systemInstruction },
        { text: userPrompt },
      ]);

      const text = result.response.text();
      if (text && text.trim().length > 0) {
        return text;
      }
    } catch (err) {
      lastError = err;
      console.warn(`[StudyFlow Backend] Model ${modelName} call failed:`, err.message);
    }
  }

  throw lastError || new Error('All candidate Gemini models failed to generate content.');
}

/**
 * Domain-Aware Educational Generator for offline demo testing or upstream fallback.
 */
function generateDemoStudySet(userInput, config = {}) {
  const cleanInput = userInput.trim();
  const lower = cleanInput.toLowerCase();

  const difficulty = config.difficulty || 'intermediate';
  const mode = config.mode || 'balanced';
  const targetCardCount = Math.min(Math.max(config.cardCount || 8, 5), 10);
  const targetQuizCount = Math.min(Math.max(config.quizCount || 5, 5), 10);

  // 1. Operating Systems
  if (lower.includes('schedul') || lower.includes('process') || lower.includes('fcfs') || lower.includes('round robin') || lower.includes('operating system')) {
    const allCards = [
      { category: 'Algorithm', question: 'What is First-Come, First-Served (FCFS) scheduling?', answer: 'A non-preemptive algorithm that allocates the CPU to processes strictly in their order of arrival.', difficulty: 'easy' },
      { category: 'Concept', question: 'What is the Convoy Effect in CPU scheduling?', answer: 'A performance bottleneck in FCFS where short processes get stuck waiting behind a long CPU-bound process.', difficulty: 'medium' },
      { category: 'Algorithm', question: 'How does Round Robin (RR) scheduling operate?', answer: 'It is a preemptive algorithm where each ready process is assigned a fixed time quantum in a circular queue.', difficulty: 'easy' },
      { category: 'Distinction', question: 'What is the key difference between preemptive and non-preemptive scheduling?', answer: 'Preemptive scheduling allows the OS to interrupt a running process, whereas non-preemptive requires the process to yield or terminate.', difficulty: 'medium' },
      { category: 'Algorithm', question: 'What is Shortest Job First (SJF) and what is its primary benefit?', answer: 'SJF schedules the process with the shortest CPU burst next, provably minimizing average waiting time.', difficulty: 'medium' },
      { category: 'Trade-off', question: 'What is process starvation in Priority Scheduling and how is it solved?', answer: 'Low-priority processes may wait indefinitely; aging (gradually increasing priority over time) prevents starvation.', difficulty: 'hard' },
      { category: 'Mechanism', question: 'What happens in Round Robin if the time quantum is set too small?', answer: 'Context-switching overhead increases dramatically, degrading overall CPU throughput.', difficulty: 'hard' },
      { category: 'Metric', question: 'What is Turnaround Time in OS scheduling?', answer: 'The total time elapsed from process submission to process completion (Waiting Time + CPU Execution Time).', difficulty: 'easy' },
      { category: 'Mechanism', question: 'What is the role of the Short-Term Scheduler (CPU Scheduler)?', answer: 'Selects which process in the ready queue is allocated the CPU for execution next.', difficulty: 'medium' },
      { category: 'Advanced', question: 'How does a Multilevel Feedback Queue (MLFQ) differ from standard multilevel queues?', answer: 'MLFQ allows processes to dynamically move between priority queues based on their observed CPU burst behavior.', difficulty: 'hard' },
    ];

    const allQuiz = [
      { category: 'Algorithm', question: 'Which scheduling algorithm is provably optimal for minimizing average waiting time?', options: ['First-Come, First-Served (FCFS)', 'Shortest Job First (SJF)', 'Round Robin (RR)', 'Priority Scheduling'], answer: 1, explanation: 'SJF executes the shortest burst times first, mathematically minimizing total waiting time.', difficulty: 'medium' },
      { category: 'Mechanism', question: 'Which parameter directly dictates the balance between response time and context-switching overhead in Round Robin?', options: ['Priority weight', 'Time quantum', 'Page size', 'Degree of multiprogramming'], answer: 1, explanation: 'The time quantum determines how frequently CPU context switches occur in Round Robin.', difficulty: 'easy' },
      { category: 'Problem', question: 'What technique prevents low-priority processes from suffering indefinite starvation?', options: ['Paging', 'Aging', 'Preemption masking', 'Thread pooling'], answer: 1, explanation: 'Aging gradually increases the priority of processes waiting in the ready queue for long periods.', difficulty: 'medium' },
      { category: 'Phenomenon', question: 'The "Convoy Effect" is most prominently associated with which CPU scheduling algorithm?', options: ['First-Come, First-Served (FCFS)', 'Round Robin with small quantum', 'Multilevel Feedback Queue', 'Shortest Remaining Time First'], answer: 0, explanation: 'In FCFS, long jobs hold the CPU while I/O-bound jobs queue up behind it.', difficulty: 'easy' },
      { category: 'Distinction', question: 'What is the fundamental difference between Shortest Job First (SJF) and Shortest Remaining Time First (SRTF)?', options: ['SJF is preemptive while SRTF is non-preemptive', 'SRTF is the preemptive version of SJF', 'SJF uses a time quantum while SRTF does not', 'SRTF applies only to real-time operating systems'], answer: 1, explanation: 'SRTF preempts the currently running job if a new job arrives with a shorter remaining burst time.', difficulty: 'hard' },
      { category: 'Metric', question: 'If a process arrives at time 0, executes for 8 ms, and finishes at time 12 ms, what is its Turnaround Time?', options: ['4 ms', '8 ms', '12 ms', '20 ms'], answer: 2, explanation: 'Turnaround Time = Completion Time - Arrival Time = 12 - 0 = 12 ms.', difficulty: 'hard' },
    ];

    return {
      title: 'Operating System Process Scheduling',
      summary: 'High-yield study deck comparing FCFS, SJF, Round Robin, time quantum dynamics, starvation prevention, and context-switching trade-offs.',
      metadata: { difficulty, mode, estimatedMinutes: 12, topics: ['FCFS & SJF', 'Round Robin & Quanta', 'Starvation & Aging', 'Turnaround Metrics'] },
      cards: allCards.slice(0, targetCardCount),
      quiz: allQuiz.slice(0, targetQuizCount),
    };
  }

  // 2. JavaScript Event Loop
  if (lower.includes('event loop') || lower.includes('javascript') || lower.includes('microtask') || lower.includes('promise') || lower.includes('call stack')) {
    const allCards = [
      { category: 'Architecture', question: 'What is the JavaScript Call Stack?', answer: 'A LIFO data structure that tracks active execution contexts and function invocations in the single thread.', difficulty: 'easy' },
      { category: 'Queue', question: 'What tasks go into the Microtask Queue?', answer: 'Promise callbacks (.then, .catch, .finally), queueMicrotask(), and MutationObserver callbacks.', difficulty: 'medium' },
      { category: 'Queue', question: 'What tasks go into the Macrotask (Task) Queue?', answer: 'setTimeout, setInterval, setImmediate, and I/O event callbacks.', difficulty: 'medium' },
      { category: 'Mechanism', question: 'When does the Event Loop drain the Microtask Queue?', answer: 'Immediately after the Call Stack empties, completely draining all microtasks before picking the next macrotask.', difficulty: 'hard' },
      { category: 'Concept', question: 'Why is JavaScript described as single-threaded with non-blocking I/O?', answer: 'The JS engine has one call stack, but delegates asynchronous operations to browser Web APIs / Node.js libuv worker threads.', difficulty: 'medium' },
      { category: 'Mechanism', question: 'What happens if a microtask continuously spawns another microtask?', answer: 'It starves the macrotask queue and UI rendering, locking up the browser thread (Microtask Starvation).', difficulty: 'hard' },
      { category: 'Distinction', question: 'What is the execution order difference between Promise.resolve() and setTimeout(fn, 0)?', answer: 'Promise.resolve() is a microtask and executes before setTimeout(fn, 0), which is a macrotask.', difficulty: 'easy' },
      { category: 'Web API', question: 'Where do DOM event listeners and timer callbacks wait before entering the Call Stack?', answer: 'They execute in Web APIs, queue their callbacks in the Task Queue, and enter the Call Stack via the Event Loop.', difficulty: 'medium' },
    ];

    const allQuiz = [
      { category: 'Execution Order', question: 'Which queue has higher execution priority once the call stack is clear?', options: ['Macrotask Queue', 'Microtask Queue', 'Timer Queue', 'I/O Poller'], answer: 1, explanation: 'The event loop must exhaust the entire microtask queue before picking the next macrotask.', difficulty: 'easy' },
      { category: 'Classification', question: 'Which of the following is scheduled into the Microtask Queue?', options: ['setTimeout()', 'Promise.prototype.then()', 'setInterval()', 'setImmediate()'], answer: 1, explanation: 'Promise resolution handlers (.then/.catch) are scheduled as microtasks.', difficulty: 'medium' },
      { category: 'Output Prediction', question: 'Given `console.log(1); setTimeout(() => console.log(2), 0); Promise.resolve().then(() => console.log(3)); console.log(4);`, what is the output?', options: ['1, 2, 3, 4', '1, 4, 2, 3', '1, 4, 3, 2', '1, 3, 4, 2'], answer: 2, explanation: 'Synchronous logs (1, 4) execute first, followed by microtask (3), and finally macrotask (2).', difficulty: 'hard' },
      { category: 'Engine', question: 'Which component provides the background thread pool for asynchronous I/O in Node.js?', options: ['V8 Engine', 'libuv', 'SpiderMonkey', 'Babel'], answer: 1, explanation: 'libuv handles the event loop and asynchronous thread pool in Node.js.', difficulty: 'medium' },
      { category: 'Browser Behavior', question: 'When does browser UI rendering (paint/layout) occur in relation to the event loop?', options: ['Before every microtask', 'Between macrotasks after the microtask queue has emptied', 'Only when the tab is hidden', 'Synchronously inside Promise handlers'], answer: 1, explanation: 'The browser performs rendering opportunities between macrotasks once all pending microtasks are flushed.', difficulty: 'hard' },
    ];

    return {
      title: 'JavaScript Event Loop & Microtasks',
      summary: 'Active learning deck on Call Stack mechanics, Web APIs, Microtask queue priority, Promises, and Macrotask timing.',
      metadata: { difficulty, mode, estimatedMinutes: 10, topics: ['Call Stack', 'Microtask Queue', 'Macrotask Queue', 'Execution Order'] },
      cards: allCards.slice(0, targetCardCount),
      quiz: allQuiz.slice(0, targetQuizCount),
    };
  }

  // 3. History: World War II
  if (lower.includes('world war') || lower.includes('ww2') || lower.includes('wwii') || lower.includes('stalingrad') || lower.includes('midway') || lower.includes('normandy') || lower.includes('el alamein')) {
    const allCards = [
      { category: 'Eastern Front', question: 'What was the significance of the Battle of Stalingrad (1942–1943)?', answer: 'It marked the decisive turning point on the Eastern Front, destroying the German Sixth Army and forcing a permanent Axis retreat.', difficulty: 'medium' },
      { category: 'Pacific Theater', question: 'Why was the Battle of Midway (1942) a pivotal naval engagement?', answer: 'The US Navy sank four Japanese aircraft carriers, halting Japanese expansion and turning the naval balance in the Pacific.', difficulty: 'medium' },
      { category: 'Western Front', question: 'What was Operation Overlord (D-Day, June 6, 1944)?', answer: 'The massive Allied amphibious invasion of Normandy, France, opening a decisive second front in Western Europe.', difficulty: 'easy' },
      { category: 'North Africa', question: 'What was the strategic outcome of the Second Battle of El Alamein (1942)?', answer: 'British forces halted Axis advances into Egypt, securing the Suez Canal and Middle Eastern oil routes.', difficulty: 'medium' },
      { category: 'Strategy', question: 'What was the Allied "Island Hopping" strategy in the Pacific?', answer: 'Bypassing heavily fortified Japanese island bases to capture strategically crucial islands closer to mainland Japan.', difficulty: 'easy' },
      { category: 'Conferences', question: 'What was decided at the Yalta Conference (1945)?', answer: 'Allied leaders (Roosevelt, Churchill, Stalin) planned the post-war division of Germany and the creation of the United Nations.', difficulty: 'hard' },
      { category: 'Air Warfare', question: 'What was the Battle of Britain (1940)?', answer: 'The first major military campaign fought entirely in the air, in which the RAF defeated the Luftwaffe, preventing Operation Sea Lion.', difficulty: 'medium' },
      { category: 'Turning Point', question: 'What took place at the Battle of the Bulge (1944–1945)?', answer: 'Hitler\'s last major offensive in the Ardennes, which failed to split Allied lines and depleted German reserves.', difficulty: 'hard' },
    ];

    const allQuiz = [
      { category: 'Pacific Theater', question: 'Which 1942 naval battle is widely considered the critical turning point in the Pacific War?', options: ['Battle of the Coral Sea', 'Battle of Midway', 'Battle of Leyte Gulf', 'Battle of Iwo Jima'], answer: 1, explanation: 'Midway crippled Japan’s carrier fleet and shifted the strategic offensive to the United States.', difficulty: 'medium' },
      { category: 'Eastern Front', question: 'The catastrophic encirclement and surrender of the German 6th Army occurred in which battle?', options: ['Battle of Moscow', 'Battle of Kursk', 'Battle of Stalingrad', 'Siege of Leningrad'], answer: 2, explanation: 'The German 6th Army was surrounded and surrendered at Stalingrad in February 1943.', difficulty: 'easy' },
      { category: 'Western Front', question: 'What was the military codename for the Allied amphibious landings in Normandy on June 6, 1944?', options: ['Operation Barbarossa', 'Operation Overlord', 'Operation Torch', 'Operation Market Garden'], answer: 1, explanation: 'Operation Overlord was the overall codename for the Normandy invasion (with Neptune as the assault phase).', difficulty: 'easy' },
      { category: 'Strategic Supply', question: 'The British victory at El Alamein in North Africa was vital primarily because it protected:', options: ['The Panama Canal', 'The Suez Canal and Middle Eastern oil', 'The Straits of Gibraltar', 'The Atlantic convoy lanes'], answer: 1, explanation: 'Securing Egypt protected Allied access to the Suez Canal and Persian Gulf oil reserves.', difficulty: 'medium' },
      { category: 'Air Warfare', question: 'Which technological advancement gave the British Royal Air Force a crucial early-warning advantage during the Battle of Britain?', options: ['Jet propulsion', 'The Dowding System using Chain Home Radar', 'Nuclear depth charges', 'Satellite imaging'], answer: 1, explanation: 'The Chain Home radar network and centralized Dowding interception system allowed the RAF to direct fighters efficiently.', difficulty: 'hard' },
    ];

    return {
      title: 'World War II: Turning Points & Strategy',
      summary: 'Structured review of key World War II campaigns including Stalingrad, Midway, D-Day, El Alamein, and the Pacific island-hopping campaign.',
      metadata: { difficulty, mode, estimatedMinutes: 12, topics: ['Midway & Pacific', 'Stalingrad & Eastern Front', 'D-Day & Western Front', 'Allied Strategy'] },
      cards: allCards.slice(0, targetCardCount),
      quiz: allQuiz.slice(0, targetQuizCount),
    };
  }

  // 4. Biology: Photosynthesis & Respiration
  if (lower.includes('photosynthesis') || lower.includes('respiration') || lower.includes('calvin') || lower.includes('krebs') || lower.includes('atp') || lower.includes('chloroplast')) {
    const allCards = [
      { category: 'Photosynthesis', question: 'Where do the light-dependent reactions of photosynthesis occur?', answer: 'In the thylakoid membranes of chloroplasts, producing ATP and NADPH while releasing O2 from water splitting.', difficulty: 'easy' },
      { category: 'Photosynthesis', question: 'What is the primary function of the Calvin Cycle (Light-Independent Reaction)?', answer: 'To fix carbon dioxide into G3P (sugars) in the chloroplast stroma using ATP and NADPH.', difficulty: 'medium' },
      { category: 'Respiration', question: 'Where does Glycolysis occur and what are its net products?', answer: 'In the cytoplasm; converts 1 glucose into 2 pyruvate, yielding a net of 2 ATP and 2 NADH without requiring oxygen.', difficulty: 'easy' },
      { category: 'Respiration', question: 'What is the primary role of the Krebs (Citric Acid) Cycle?', answer: 'To oxidize acetyl-CoA in the mitochondrial matrix, producing NADH, FADH2, and ATP for the electron transport chain.', difficulty: 'medium' },
      { category: 'Bioenergetics', question: 'How does Oxidative Phosphorylation generate ATP?', answer: 'Electrons flow through the ETC, creating a proton gradient across the inner mitochondrial membrane that drives ATP synthase.', difficulty: 'hard' },
    ];

    const allQuiz = [
      { category: 'Photosynthesis', question: 'Which molecule provides the replacement electrons for Photosystem II during light-dependent reactions?', options: ['Carbon dioxide (CO2)', 'Water (H2O)', 'Glucose (C6H12O6)', 'NADPH'], answer: 1, explanation: 'Photolysis splits water molecules into electrons, protons, and oxygen gas.', difficulty: 'medium' },
      { category: 'Cellular Respiration', question: 'Which phase of cellular respiration produces the largest quantity of ATP molecules?', options: ['Glycolysis', 'Pyruvate Oxidation', 'Krebs Cycle', 'Oxidative Phosphorylation (Electron Transport Chain)'], answer: 3, explanation: 'Oxidative phosphorylation generates approximately 26–28 of the ~30–32 ATP produced per glucose.', difficulty: 'easy' },
      { category: 'Enzyme Action', question: 'The enzyme RuBisCO is responsible for carbon fixation in which cellular compartment?', options: ['Thylakoid lumen', 'Chloroplast stroma', 'Mitochondrial matrix', 'Cytoplasm'], answer: 1, explanation: 'The Calvin cycle and RuBisCO operate within the fluid stroma of the chloroplast.', difficulty: 'medium' },
      { category: 'Respiration', question: 'In the absence of oxygen, how do cells regenerate NAD+ to keep glycolysis functioning?', options: ['Oxidative phosphorylation', 'Fermentation (Lactic acid or Alcoholic)', 'The Calvin cycle', 'Beta-oxidation'], answer: 1, explanation: 'Fermentation transfers electrons from NADH to pyruvate/derivatives to regenerate NAD+.', difficulty: 'medium' },
    ];

    return {
      title: 'Photosynthesis & Cellular Respiration',
      summary: 'Comparative study set detailing light-dependent reactions, Calvin cycle, Glycolysis, Krebs cycle, and Chemiosmosis.',
      metadata: { difficulty, mode, estimatedMinutes: 12, topics: ['Light Reactions & Calvin Cycle', 'Glycolysis & Fermentation', 'Krebs Cycle', 'Oxidative Phosphorylation'] },
      cards: allCards.slice(0, targetCardCount),
      quiz: allQuiz.slice(0, targetQuizCount),
    };
  }

  // Generic fallback
  const topicTitle = cleanInput.length > 35 ? cleanInput.slice(0, 32) + '...' : cleanInput;
  const cards = [];
  const quiz = [];

  for (let i = 1; i <= targetCardCount; i++) {
    cards.push({
      category: i % 3 === 0 ? 'Application' : i % 2 === 0 ? 'Mechanism' : 'Core Concept',
      question: `Key Concept #${i} in ${topicTitle}: What are the fundamental principles and operational mechanisms?`,
      answer: `This concept outlines the core definition, primary constraints, and practical methodology required for understanding ${topicTitle}.`,
      difficulty: i <= 3 ? 'easy' : i <= 7 ? 'medium' : 'hard',
    });
  }

  for (let j = 1; j <= targetQuizCount; j++) {
    quiz.push({
      category: 'Concept Review',
      question: `Question #${j}: Which of the following is the most accurate statement regarding ${topicTitle}?`,
      options: [
        `It operates under structured principles ensuring consistent execution and reliability.`,
        `It functions with unvalidated arbitrary runtime exceptions.`,
        `It bypasses all system constraints without input verification.`,
        `It produces non-deterministic results without defined specifications.`
      ],
      answer: 0,
      explanation: `Systematic principles and strict validation ensure deterministic behavior and reliable outcomes in ${topicTitle}.`,
      difficulty: j <= 2 ? 'easy' : j <= 4 ? 'medium' : 'hard',
    });
  }

  return {
    title: `Study Guide: ${topicTitle}`,
    summary: `Structured active learning set covering key definitions, operational principles, and review questions for ${topicTitle}.`,
    metadata: { difficulty, mode, estimatedMinutes: 10, topics: ['Foundational Concepts', 'Mechanisms', 'Practical Applications'] },
    cards,
    quiz,
  };
}

/**
 * Generates grounded Mock Viva questions for the oral examination.
 */
function generateDemoVivaQuestions(studyData, config = {}) {
  const title = studyData?.title || 'Study Material';
  const lower = title.toLowerCase();
  const difficulty = config.difficulty || 'intermediate';
  const targetCount = Math.min(Math.max(config.questionCount || 5, 3), 10);

  if (lower.includes('process') || lower.includes('schedul') || lower.includes('operating system') || lower.includes('fcfs') || lower.includes('round robin')) {
    const questions = [
      { id: 'viva-q-1', category: 'Algorithm Mechanics', question: 'Can you explain how Round Robin scheduling works, and what role the time quantum plays?', type: 'explanation', difficulty: 'intermediate', expectedKeyPoints: ['Preemptive circular queue', 'Fixed time quantum per process', 'Context switch occurs when quantum expires'] },
      { id: 'viva-q-2', category: 'Comparative Analysis', question: 'How does Shortest Job First compare to FCFS, and why does FCFS suffer from the Convoy Effect?', type: 'comparison', difficulty: 'intermediate', expectedKeyPoints: ['SJF minimizes average waiting time', 'FCFS is strictly arrival order', 'Long CPU bound jobs block short I/O jobs in FCFS'] },
      { id: 'viva-q-3', category: 'Problem Solving & Starvation', question: 'Suppose we use Priority Scheduling in a busy server. What problem might occur for low-priority tasks, and how can the OS solve it?', type: 'why', difficulty: 'advanced', expectedKeyPoints: ['Starvation or indefinite blocking', 'Solution is Aging (gradually increasing priority over time)'] },
      { id: 'viva-q-4', category: 'System Architecture', question: 'What is the exact distinction between preemptive and non-preemptive scheduling from an OS kernel perspective?', type: 'definition', difficulty: 'beginner', expectedKeyPoints: ['Preemptive allows kernel interrupt while running', 'Non-preemptive lets process run until voluntary yield or termination'] },
      { id: 'viva-q-5', category: 'Engineering Trade-offs', question: 'If you were designing a real-time interactive operating system, why would you not set the Round Robin time quantum to 1 microsecond?', type: 'scenario', difficulty: 'advanced', expectedKeyPoints: ['Excessive context switching overhead', 'CPU spends more time switching states than executing user code', 'Overall system throughput drops significantly'] },
    ];
    return { title: `Mock Viva: ${title}`, questions: questions.slice(0, targetCount) };
  }

  if (lower.includes('event loop') || lower.includes('javascript') || lower.includes('microtask')) {
    const questions = [
      { id: 'viva-q-1', category: 'Call Stack & Asynchrony', question: 'Walk me through what happens when JavaScript encounters an asynchronous operation like a Promise or setTimeout.', type: 'explanation', difficulty: 'intermediate', expectedKeyPoints: ['Single threaded call stack', 'Web APIs execute asynchronous timers/requests', 'Callbacks are enqueued in Microtask or Task queues'] },
      { id: 'viva-q-2', category: 'Queue Priority', question: 'Explain the priority difference between the Microtask Queue and the Macrotask Queue during an Event Loop cycle.', type: 'comparison', difficulty: 'intermediate', expectedKeyPoints: ['Microtasks have higher priority', 'Event loop exhausts all microtasks before picking next macrotask', 'Promise callbacks execute before next timer'] },
      { id: 'viva-q-3', category: 'Failure Modes', question: 'What is microtask starvation, and how could a recursive Promise or queueMicrotask lock the browser UI?', type: 'why', difficulty: 'advanced', expectedKeyPoints: ['Microtasks continuously added keep the queue non-empty', 'Event loop never proceeds to rendering or task queue', 'UI freezes'] },
    ];
    return { title: `Mock Viva: ${title}`, questions: questions.slice(0, targetCount) };
  }

  // General grounded questions
  const questions = [
    { id: 'viva-q-1', category: 'Core Concept', question: `Let's start with the fundamentals. Can you define what ${title} is and explain its primary objective?`, type: 'definition', difficulty: 'beginner', expectedKeyPoints: ['Core definition', 'Primary use case', 'Operational objective'] },
    { id: 'viva-q-2', category: 'Mechanism & Architecture', question: `How do the main mechanisms in ${title} operate together to produce deterministic results?`, type: 'explanation', difficulty: 'intermediate', expectedKeyPoints: ['Key component interactions', 'State management', 'Execution lifecycle'] },
    { id: 'viva-q-3', category: 'Trade-offs & Constraints', question: `What are the most significant trade-offs or constraints an engineer must evaluate when applying ${title}?`, type: 'why', difficulty: 'advanced', expectedKeyPoints: ['Resource utilization', 'Complexity vs speed', 'Edge case failure modes'] },
    { id: 'viva-q-4', category: 'Practical Scenario', question: `Imagine a real-world scenario where ${title} fails unexpectedly. How would you diagnose and resolve the issue?`, type: 'scenario', difficulty: 'advanced', expectedKeyPoints: ['Systematic debugging', 'Validation enforcement', 'Graceful recovery'] },
  ];
  return { title: `Mock Viva: ${title}`, questions: questions.slice(0, targetCount) };
}

/**
 * Generates a semantic evaluation for an oral viva answer.
 */
function generateDemoVivaEvaluation(question, studentAnswer, isFollowUp = false) {
  const text = (studentAnswer || '').trim().toLowerCase();
  const wordCount = text.split(/\s+/).length;

  if (wordCount < 4) {
    return {
      evaluation: { correctness: 3, completeness: 3, clarity: 4, relevance: 5, overall: 3 },
      classification: 'incorrect',
      feedback: 'That explanation is too brief. Can you elaborate on the underlying mechanism?',
      strengths: ['Attempted a response.'],
      missingConcepts: ['Need deeper explanation of the core principles.', 'Missing key technical terms.'],
      followUpRequired: !isFollowUp,
      followUpQuestion: isFollowUp ? null : `Can you describe in more detail how this actually operates in practice?`,
      nextDifficultyAdjustment: 'decrease',
    };
  }

  // Basic semantic check on key topics
  const hasSpecificKeywords = ['quantum', 'preempt', 'fcfs', 'round robin', 'starvation', 'aging', 'microtask', 'promise', 'stack', 'index', 'acid', 'stalingrad', 'midway', 'atp', 'chloroplast', 'calvin'].some((k) => text.includes(k));

  if (hasSpecificKeywords || wordCount >= 18) {
    const isVeryStrong = wordCount >= 25 && (text.includes('because') || text.includes('which') || text.includes('when') || text.includes('preempt') || text.includes('queue'));
    if (isVeryStrong) {
      return {
        evaluation: { correctness: 9, completeness: 9, clarity: 9, relevance: 10, overall: 9 },
        classification: 'correct',
        feedback: 'Excellent explanation! You clearly articulated both the mechanism and the rationale.',
        strengths: ['Clear conceptual clarity', 'Good technical precision', 'Concise and relevant reasoning'],
        missingConcepts: [],
        followUpRequired: false,
        followUpQuestion: null,
        nextDifficultyAdjustment: 'increase',
      };
    }

    return {
      evaluation: { correctness: 7, completeness: 7, clarity: 8, relevance: 8, overall: 7 },
      classification: 'partially_correct',
      feedback: 'Good answer. You captured the main concept well, though one technical detail could be sharper.',
      strengths: ['Understands the fundamental behavior', 'Used appropriate context'],
      missingConcepts: ['Could clarify the exact trigger or edge condition.'],
      followUpRequired: !isFollowUp,
      followUpQuestion: isFollowUp ? null : 'How does that behavior change if system load or queue length increases significantly?',
      nextDifficultyAdjustment: 'maintain',
    };
  }

  return {
    evaluation: { correctness: 5, completeness: 5, clarity: 6, relevance: 6, overall: 5 },
    classification: 'partially_correct',
    feedback: 'You are on the right track, but think about how the components interact step by step.',
    strengths: ['Identified the general topic area'],
    missingConcepts: ['Missing direct explanation of the operational mechanism.'],
    followUpRequired: !isFollowUp,
    followUpQuestion: isFollowUp ? null : 'What is the primary reason the system is designed this way rather than using a simple sequential approach?',
    nextDifficultyAdjustment: 'maintain',
  };
}

/**
 * POST /api/generate
 */
app.post('/api/generate', async (req, res) => {
  const { input, config } = req.body;

  if (!input || typeof input !== 'string' || input.trim().length === 0) {
    return res.status(400).json({
      error: 'Please enter a topic or paste study notes before generating.',
    });
  }

  const trimmedInput = input.trim();
  if (trimmedInput.length < 2) {
    return res.status(400).json({
      error: 'Input is too short. Please provide at least 2 characters.',
    });
  }

  if (trimmedInput.length > 15000) {
    return res.status(400).json({
      error: 'Input exceeds the maximum length of 15,000 characters. Please condense your notes.',
    });
  }

  const studyConfig = {
    difficulty: ['beginner', 'intermediate', 'advanced'].includes(config?.difficulty?.toLowerCase())
      ? config.difficulty.toLowerCase()
      : 'intermediate',
    cardCount: [5, 8, 10].includes(Number(config?.cardCount)) ? Number(config.cardCount) : 8,
    quizCount: [5, 8, 10].includes(Number(config?.quizCount)) ? Number(config.quizCount) : 5,
    mode: ['balanced', 'concept', 'exam'].includes(config?.mode?.toLowerCase())
      ? config.mode.toLowerCase()
      : 'balanced',
  };

  const apiKey = process.env.GEMINI_API_KEY;
  const isKeyMissing = !apiKey || apiKey === 'your_gemini_api_key_here' || apiKey.trim() === '';

  if (isKeyMissing) {
    console.log(`[StudyFlow Backend] Generating demo study set for: "${trimmedInput.slice(0, 40)}" (Cards: ${studyConfig.cardCount}, Quiz: ${studyConfig.quizCount})`);
    const demoData = generateDemoStudySet(trimmedInput, studyConfig);
    const validation = validateAndSanitizeStudySet(demoData, studyConfig);

    await new Promise((r) => setTimeout(r, 600));

    return res.status(200).json({
      success: true,
      data: validation.sanitizedData,
      isDemo: true,
      message: 'Generated via Demo Engine. Add GEMINI_API_KEY to .env for live Gemini model.',
    });
  }

  try {
    const systemInstruction = `You are an expert curriculum designer and educational assessor.
Convert the user's provided notes or topic into a structured active learning study set.

CONFIGURATION SETTINGS:
- Difficulty Target: ${studyConfig.difficulty.toUpperCase()}
- Flashcard Count: Exactly ${studyConfig.cardCount} cards
- Quiz Question Count: Exactly ${studyConfig.quizCount} questions
- Learning Mode: ${studyConfig.mode.toUpperCase()}

STRICT RULES:
1. GROUNDING: Ground content strictly in the user's topic.
2. ACCURACY: Every flashcard question must be directly answered by its answer.
3. UNIQUENESS: No duplicate questions or answers.
4. QUIZ: Exactly 4 options per quiz question, answer index 0..3, and clear explanation.
5. JSON: Respond ONLY with valid JSON conforming to the schema.

SCHEMA:
{
  "title": "Title (string)",
  "summary": "1-2 sentence overview (string)",
  "metadata": {
    "difficulty": "${studyConfig.difficulty}",
    "mode": "${studyConfig.mode}",
    "estimatedMinutes": 15,
    "topics": ["Topic 1", "Topic 2", "Topic 3"]
  },
  "cards": [{ "category": "Tag", "question": "Question", "answer": "Answer", "difficulty": "easy|medium|hard" }],
  "quiz": [{ "category": "Tag", "question": "Question", "options": ["A","B","C","D"], "answer": 0, "explanation": "Why", "difficulty": "easy|medium|hard" }]
}`;

    const userPrompt = `USER INPUT:\n"""\n${trimmedInput}\n"""`;

    let rawResponseText;
    try {
      rawResponseText = await callGeminiWithFallback(apiKey, systemInstruction, userPrompt);
    } catch (apiErr) {
      console.warn('[StudyFlow Backend] Gemini API unavailable, activating graceful domain fallback generator:', apiErr.message);
      const fallbackData = generateDemoStudySet(trimmedInput, studyConfig);
      const validation = validateAndSanitizeStudySet(fallbackData, studyConfig);
      return res.status(200).json({
        success: true,
        data: validation.sanitizedData,
        isDemo: true,
      });
    }

    const cleanedJson = cleanRawJsonResponse(rawResponseText);
    let parsedData = JSON.parse(cleanedJson);
    const validation = validateAndSanitizeStudySet(parsedData, studyConfig);

    if (!validation.valid) {
      const fallbackData = generateDemoStudySet(trimmedInput, studyConfig);
      const fallbackVal = validateAndSanitizeStudySet(fallbackData, studyConfig);
      return res.status(200).json({ success: true, data: fallbackVal.sanitizedData, isDemo: true });
    }

    return res.status(200).json({ success: true, data: validation.sanitizedData });
  } catch (err) {
    console.error('Error generating study set:', err);
    const fallbackData = generateDemoStudySet(trimmedInput, studyConfig);
    const validation = validateAndSanitizeStudySet(fallbackData, studyConfig);
    return res.status(200).json({ success: true, data: validation.sanitizedData, isDemo: true });
  }
});

/**
 * POST /api/viva/generate-questions
 * Generates grounded Viva examination questions for oral interview
 */
app.post('/api/viva/generate-questions', async (req, res) => {
  const { studyData, config } = req.body;

  if (!studyData || !studyData.title) {
    return res.status(400).json({ error: 'Study set data is required to create viva questions.' });
  }

  const vivaConfig = {
    difficulty: config?.difficulty || 'intermediate',
    interviewType: config?.interviewType || 'mixed',
    questionCount: [3, 5, 10].includes(Number(config?.questionCount)) ? Number(config.questionCount) : 5,
  };

  const apiKey = process.env.GEMINI_API_KEY;
  const isKeyMissing = !apiKey || apiKey === 'your_gemini_api_key_here' || apiKey.trim() === '';

  if (isKeyMissing) {
    const demoViva = generateDemoVivaQuestions(studyData, vivaConfig);
    await new Promise((r) => setTimeout(r, 500));
    return res.status(200).json({ success: true, data: demoViva, isDemo: true });
  }

  try {
    const systemInstruction = `You are a strict, professional academic examiner conducting a realistic oral viva examination.
Your goal is to test deep conceptual understanding, mechanisms, edge cases, and engineering trade-offs.

RULES:
1. GROUNDING: Every question MUST be strictly relevant to the study title: "${studyData.title}".
2. QUESTION MIX: Generate a balanced mix of question types: definition, explanation, comparison, why, scenario.
3. CONVERSATIONAL EXAMINER: Phrase questions naturally as an examiner speaking directly to a student (e.g., "Can you explain how...", "Why would you choose X over Y?").
4. KEY POINTS: For each question, list 2-3 expected key concepts the examiner will look for in a good answer.
5. NO TRIVIA: Avoid superficial multiple-choice trivia. Ask open-ended questions suitable for verbal explanation.
6. Return ONLY valid JSON matching this schema:
{
  "title": "Viva: ${studyData.title}",
  "questions": [
    {
      "id": "viva-q-1",
      "category": "Subtopic tag (string)",
      "question": "Clear spoken oral question (string)",
      "type": "definition|explanation|comparison|why|scenario|technical",
      "difficulty": "${vivaConfig.difficulty}",
      "expectedKeyPoints": ["Point 1", "Point 2", "Point 3"]
    }
  ]
}`;

    // const userPrompt = `TOPIC: ${studyData.title}\nSUMMARY: ${studyData.summary || ''}\nTOPICS: ${(studyData.metadata?.topics || []).join(', ')}\nCOUNT: ${vivaConfig.questionCount} questions\nDIFFICULTY: ${vivaConfig.difficulty}`;
    const userPrompt = `TOPIC: ${studyData.title}
SUMMARY: ${studyData.summary || ''}
TOPICS: ${(studyData.metadata?.topics || []).join(', ')}
COUNT: ${vivaConfig.questionCount} questions
DIFFICULTY: ${vivaConfig.difficulty}`;

    let rawText;
    try {
      rawText = await callGeminiWithFallback(apiKey, systemInstruction, userPrompt);
    } catch (apiErr) {
      console.warn('[StudyFlow Backend] Gemini viva question call failed, using fallback:', apiErr.message);
      const demoViva = generateDemoVivaQuestions(studyData, vivaConfig);
      return res.status(200).json({ success: true, data: demoViva, isDemo: true });
    }

    const cleaned = cleanRawJsonResponse(rawText);
    const parsed = JSON.parse(cleaned);

    return res.status(200).json({ success: true, data: parsed });
  } catch (err) {
    console.error('Error in viva question generation:', err);
    const demoViva = generateDemoVivaQuestions(studyData, vivaConfig);
    return res.status(200).json({ success: true, data: demoViva, isDemo: true });
  }
});

/**
 * POST /api/viva/evaluate
 * Semantically evaluates a student's verbal explanation and decides on follow-ups
 */
app.post('/api/viva/evaluate', async (req, res) => {
  const { studyContext, question, studentAnswer, isFollowUp, history } = req.body;

  if (!studentAnswer || typeof studentAnswer !== 'string' || studentAnswer.trim().length === 0) {
    return res.status(400).json({ error: 'Answer transcript is required for evaluation.' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  const isKeyMissing = !apiKey || apiKey === 'your_gemini_api_key_here' || apiKey.trim() === '';

  if (isKeyMissing) {
    const demoEval = generateDemoVivaEvaluation(question, studentAnswer, isFollowUp);
    await new Promise((r) => setTimeout(r, 600));
    return res.status(200).json({ success: true, data: demoEval, isDemo: true });
  }

  try {
    const systemInstruction = `You are an expert AI examiner evaluating a student's verbal response in a real-time Mock Viva oral exam.

CRITICAL INSTRUCTIONS:
1. SEMANTIC EVALUATION: Evaluate the conceptual meaning, depth, and accuracy of the answer. DO NOT simply count keyword matches.
2. NATURAL FEEDBACK: Write 1-2 spoken sentences as a real human examiner (e.g. "Good explanation, you nailed the core mechanism. But what about the context switch overhead?"). Avoid robotic phrases like "Your answer has been processed".
3. FOLLOW-UP DECISION:
   - If the user gave a partial answer or missed a crucial mechanism AND this is NOT already a follow-up (isFollowUp = false), set followUpRequired = true and write a focused followUpQuestion.
   - If the user answered well, or if isFollowUp = true, set followUpRequired = false and followUpQuestion = null.
4. METRICS (0-10): Grade correctness, completeness, clarity, relevance, overall.
5. CLASSIFICATION: "correct" (overall >= 8), "partially_correct" (5-7), "incorrect" (< 5).
6. Return ONLY valid JSON matching this schema:
{
  "evaluation": {
    "correctness": 8,
    "completeness": 7,
    "clarity": 9,
    "relevance": 9,
    "overall": 8
  },
  "classification": "correct|partially_correct|incorrect",
  "feedback": "Spoken natural feedback from examiner (string)",
  "strengths": ["Strengths list"],
  "missingConcepts": ["Missing technical points"],
  "followUpRequired": false,
  "followUpQuestion": null,
  "nextDifficultyAdjustment": "increase|maintain|decrease"
}`;

    const userPrompt = `EXAMINATION CONTEXT: ${studyContext?.title || ''}
QUESTION: ${question?.question || ''}
EXPECTED KEY POINTS: ${(question?.expectedKeyPoints || []).join('; ')}
STUDENT SPOKEN ANSWER: "${studentAnswer}"
IS FOLLOW-UP: ${Boolean(isFollowUp)}`;

    let rawText;
    try {
      rawText = await callGeminiWithFallback(apiKey, systemInstruction, userPrompt);
    } catch (apiErr) {
      console.warn('[StudyFlow Backend] Gemini viva evaluation call failed, using fallback:', apiErr.message);
      const demoEval = generateDemoVivaEvaluation(question, studentAnswer, isFollowUp);
      return res.status(200).json({ success: true, data: demoEval, isDemo: true });
    }

    const cleaned = cleanRawJsonResponse(rawText);
    const parsed = JSON.parse(cleaned);

    return res.status(200).json({ success: true, data: parsed });
  } catch (err) {
    console.error('Error in viva evaluation:', err);
    const demoEval = generateDemoVivaEvaluation(question, studentAnswer, isFollowUp);
    return res.status(200).json({ success: true, data: demoEval, isDemo: true });
  }
});

/**
 * Study Room REST Validation Endpoint
 */
app.get('/api/room/:roomId', (req, res) => {
  const roomId = (req.params.roomId || '').trim().toUpperCase();
  const roomState = roomManager.getSerializableRoomState(roomId);
  if (!roomState) {
    return res.status(404).json({ success: false, error: 'Room not found or has ended.' });
  }
  return res.json({
    success: true,
    room: {
      id: roomState.id,
      name: roomState.name,
      topic: roomState.topic,
      participantCount: roomState.participants.length,
      maxParticipants: roomState.maxParticipants,
      isFull: roomState.participants.length >= roomState.maxParticipants,
    },
  });
});

/**
 * Socket.IO Real-Time Event Handlers
 */
io.on('connection', (socket) => {
  console.log(`[Socket.IO] Client connected: ${socket.id}`);

  // 1. Room Creation
  socket.on('room:create', (payload, callback) => {
    try {
      const room = roomManager.createRoom(payload || {}, socket);
      const roomState = roomManager.getSerializableRoomState(room.id);
      if (typeof callback === 'function') {
        callback({ success: true, roomId: room.id, roomState });
      }
      socket.emit('room:state-update', roomState);
    } catch (err) {
      console.error('[Socket.IO] Error creating room:', err);
      if (typeof callback === 'function') {
        callback({ success: false, error: 'Failed to create study room.' });
      }
    }
  });

  // 2. Room Joining
  socket.on('room:join', ({ roomId, userName }, callback) => {
    try {
      const result = roomManager.joinRoom(roomId, userName, socket);
      if (!result.success) {
        if (typeof callback === 'function') callback({ success: false, error: result.error });
        return;
      }

      const roomState = roomManager.getSerializableRoomState(result.room.id);
      if (typeof callback === 'function') {
        callback({
          success: true,
          roomId: result.room.id,
          participant: result.participant,
          roomState,
        });
      }

      // Notify other peers in room
      socket.to(result.room.id).emit('room:participant-joined', {
        participant: result.participant,
        roomState,
      });

      if (result.joinMsg) {
        io.to(result.room.id).emit('chat:message', result.joinMsg);
      }

      io.to(result.room.id).emit('room:state-update', roomState);
    } catch (err) {
      console.error('[Socket.IO] Error joining room:', err);
      if (typeof callback === 'function') {
        callback({ success: false, error: 'Could not join room.' });
      }
    }
  });

  // 3. Room Leaving
  socket.on('room:leave', () => {
    handleUserDisconnect(socket);
  });

  socket.on('disconnect', () => {
    console.log(`[Socket.IO] Client disconnected: ${socket.id}`);
    handleUserDisconnect(socket);
  });

  function handleUserDisconnect(s) {
    const leaveResult = roomManager.leaveRoom(s.id);
    if (!leaveResult) return;

    const { roomId, departingId, departingName, newHostId, room, leaveMsg, roomEnded } = leaveResult;

    if (roomEnded) {
      io.to(roomId).emit('room:ended', { message: 'All participants have left the room.' });
      return;
    }

    if (leaveMsg) {
      io.to(roomId).emit('chat:message', leaveMsg);
    }

    const updatedState = roomManager.getSerializableRoomState(roomId);
    io.to(roomId).emit('room:participant-left', {
      participantId: departingId,
      participantName: departingName,
      newHostId,
      roomState: updatedState,
    });
    io.to(roomId).emit('room:state-update', updatedState);
  }

  // 4. WebRTC Mesh Signaling
  socket.on('webrtc:offer', ({ targetId, sdp }) => {
    if (targetId && sdp) {
      io.to(targetId).emit('webrtc:offer', {
        senderId: socket.id,
        sdp,
      });
    }
  });

  socket.on('webrtc:answer', ({ targetId, sdp }) => {
    if (targetId && sdp) {
      io.to(targetId).emit('webrtc:answer', {
        senderId: socket.id,
        sdp,
      });
    }
  });

  socket.on('webrtc:ice-candidate', ({ targetId, candidate }) => {
    if (targetId && candidate) {
      io.to(targetId).emit('webrtc:ice-candidate', {
        senderId: socket.id,
        candidate,
      });
    }
  });

  // Media state broadcast (mic, camera, live speaking detection)
  socket.on('webrtc:media-state', ({ roomId, micEnabled, cameraEnabled, isSpeaking }) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const room = roomManager.rooms.get(cleanRoomId);
    if (room) {
      const p = room.participants.get(socket.id);
      if (p) {
        if (typeof micEnabled === 'boolean') p.micEnabled = micEnabled;
        if (typeof cameraEnabled === 'boolean') p.cameraEnabled = cameraEnabled;
        if (typeof isSpeaking === 'boolean') p.isSpeaking = isSpeaking;
      }
      socket.to(cleanRoomId).emit('webrtc:media-state-updated', {
        participantId: socket.id,
        micEnabled: p?.micEnabled,
        cameraEnabled: p?.cameraEnabled,
        isSpeaking: p?.isSpeaking,
      });
    }
  });

  // 5. Real-Time Chat
  socket.on('chat:send', ({ roomId, message, userName }) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const room = roomManager.rooms.get(cleanRoomId);
    if (!room) return;

    const sanitized = sanitizeMessage(message);
    if (!sanitized) return;

    const chatMsg = {
      id: `chat-${Date.now()}-${socket.id.slice(0, 4)}`,
      roomId: cleanRoomId,
      userId: socket.id,
      userName: userName || room.participants.get(socket.id)?.name || 'Student',
      message: sanitized,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    room.chatMessages.push(chatMsg);
    io.to(cleanRoomId).emit('chat:message', chatMsg);
  });

  // 6. Group Quiz Synchronization
  socket.on('quiz:start', ({ roomId }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = roomManager.startGroupQuiz(cleanRoomId, socket.id);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
      if (res.quizStartMsg) io.to(cleanRoomId).emit('chat:message', res.quizStartMsg);
    }
  });

  socket.on('quiz:submit-answer', ({ roomId, optionIndex }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = roomManager.submitQuizAnswer(cleanRoomId, socket.id, optionIndex);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
    }
  });

  socket.on('quiz:reveal', ({ roomId }) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = roomManager.revealQuizQuestion(cleanRoomId, socket.id);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
    }
  });

  socket.on('quiz:next', ({ roomId }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = roomManager.nextQuizQuestion(cleanRoomId, socket.id);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
      if (res.finishMsg) io.to(cleanRoomId).emit('chat:message', res.finishMsg);
    }
  });

  // 7. Grounded AI Study Moderator
  socket.on('ai:ask', async ({ roomId, userQuery, userName }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = await roomManager.askAiModerator(cleanRoomId, userQuery, userName);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('chat:message', res.aiMsg);
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
    }
  });

  // 8. AI Group Challenge
  socket.on('ai:challenge-start', async ({ roomId }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = await roomManager.startAiChallenge(cleanRoomId, socket.id);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
      if (res.challengeMsg) io.to(cleanRoomId).emit('chat:message', res.challengeMsg);
    }
  });

  socket.on('ai:challenge-analyze', ({ roomId }, callback) => {
    const cleanRoomId = (roomId || '').trim().toUpperCase();
    const res = roomManager.revealAiChallengeAnalysis(cleanRoomId, socket.id);
    if (typeof callback === 'function') callback(res);
    if (res.success) {
      io.to(cleanRoomId).emit('room:state-update', res.roomState);
      if (res.analysisMsg) io.to(cleanRoomId).emit('chat:message', res.analysisMsg);
    }
  });
});

httpServer.listen(PORT, () => {
  console.log(`[StudyFlow Backend] Server running with Socket.IO on http://localhost:${PORT}`);
});

